<?php

namespace Database\Seeders;

use App\Models\Tour;
use App\Models\ImageTour;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ImageTourSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Tour::where('id',10)->first()->image_tour()->createMany([
            [
                'image'=>'img/korean/hanquoc1.jpg',
            ],
            [
                'image'=>'img/korean/hanquoc2.jpg',
            ],
            [
                'image'=>'img/korean/hanquoc3.jpg',
            ],
            [
                'image'=>'img/korean/hanquoc4.jpg',
            ],
            [
                'image'=>'img/korean/hanquoc5.jpg',
            ],
            [
                'image'=>'img/korean/hanquoc6.jpg',
            ],
            [
                'image'=>'img/korean/hanquoc7.jpg',
            ],
            [
                'image'=>'img/korean/hanquoc8.jpg',
            ],
            [
                'image'=>'img/korean/hanquoc9.jpg',
            ],
            [
                'image'=>'img/korean/hanquoc10.jpg',
            ],
            [
                'image'=>'img/korean/hanquoc11.jpg',
            ],
            [
                'image'=>'img/korean/hanquoc12.jpg',
            ],
        ]);
        Tour::where('id',2)->first()->image_tour()->createMany([
            [
                'image'=>'img/02/01.jpg',
            ],
            [
                'image'=>'img/02/02.jpg',
            ],
            [
                'image'=>'img/02/03.jpg',
            ],
            [
                'image'=>'img/02/04.jpg',
            ],
            [
                'image'=>'img/02/05.jpg',
            ],
            [
                'image'=>'img/02/06.jpg',
            ],
            [
                'image'=>'img/02/07.jpg',
            ],
            [
                'image'=>'img/02/08.jpg',
            ],
            [
                'image'=>'img/02/09.jpg',
            ],
            [
                'image'=>'img/02/10.jpg',
            ],
            [
                'image'=>'img/02/11.jpg',
            ],
            [
                'image'=>'img/02/12.jpg',
            ],
        ]);

        Tour::where('id',3)->first()->image_tour()->createMany([
            [
                'image'=>'img/03/01.jpg',
            ],
            [
                'image'=>'img/03/02.jpg',
            ],
            [
                'image'=>'img/03/03.jpg',
            ],
            [
                'image'=>'img/03/04.jpg',
            ],
            [
                'image'=>'img/03/05.jpg',
            ],
            [
                'image'=>'img/03/06.jpg',
            ],
            [
                'image'=>'img/03/07.jpg',
            ],
            [
                'image'=>'img/03/08.jpg',
            ],
            [
                'image'=>'img/03/09.jpg',
            ],
            [
                'image'=>'img/03/10.jpg',
            ],
            [
                'image'=>'img/03/11.jpg',
            ],
            [
                'image'=>'img/03/12.jpg',
            ],
        ]);

        Tour::where('id',4)->first()->image_tour()->createMany([
            [
                'image'=>'img/04/01.jpg',
            ],
            [
                'image'=>'img/04/02.jpg',
            ],
            [
                'image'=>'img/04/03.jpg',
            ],
            [
                'image'=>'img/04/04.jpg',
            ],
            [
                'image'=>'img/04/05.jpg',
            ],
            [
                'image'=>'img/04/06.jpg',
            ],
            [
                'image'=>'img/04/07.jpg',
            ],
            [
                'image'=>'img/04/08.jpg',
            ],
            [
                'image'=>'img/04/09.jpg',
            ],
            [
                'image'=>'img/04/10.jpg',
            ],
            [
                'image'=>'img/04/11.jpg',
            ],
            [
                'image'=>'img/04/12.jpg',
            ],
        ]);

        Tour::where('id',5)->first()->image_tour()->createMany([
            [
                'image'=>'img/05/01.jpg',
            ],
            [
                'image'=>'img/05/02.jpg',
            ],
            [
                'image'=>'img/05/03.jpg',
            ],
            [
                'image'=>'img/05/04.jpg',
            ],
            [
                'image'=>'img/05/05.jpg',
            ],
            [
                'image'=>'img/05/06.jpg',
            ],
            [
                'image'=>'img/05/07.jpg',
            ],
            [
                'image'=>'img/05/08.jpg',
            ],
            [
                'image'=>'img/05/09.jpg',
            ],
            [
                'image'=>'img/05/10.jpg',
            ],
            [
                'image'=>'img/05/11.jpg',
            ],
            [
                'image'=>'img/05/12.jpg',
            ],
        ]);

        Tour::where('id',6)->first()->image_tour()->createMany([
            [
                'image'=>'img/06/01.jpg',
            ],
            [
                'image'=>'img/06/02.jpg',
            ],
            [
                'image'=>'img/06/03.jpg',
            ],
            [
                'image'=>'img/06/04.jpg',
            ],
            [
                'image'=>'img/06/05.jpg',
            ],
            [
                'image'=>'img/06/06.jpg',
            ],
            [
                'image'=>'img/06/07.jpg',
            ],
            [
                'image'=>'img/06/08.jpg',
            ],
            [
                'image'=>'img/06/09.jpg',
            ],
            [
                'image'=>'img/06/10.jpg',
            ],
            [
                'image'=>'img/06/11.jpg',
            ],
            [
                'image'=>'img/06/12.jpg',
            ],
        ]);

        Tour::where('id',7)->first()->image_tour()->createMany([
            [
                'image'=>'img/07/01.jpg',
            ],
            [
                'image'=>'img/07/02.jpg',
            ],
            [
                'image'=>'img/07/03.jpg',
            ],
            [
                'image'=>'img/07/04.jpg',
            ],
            [
                'image'=>'img/07/05.jpg',
            ],
            [
                'image'=>'img/07/06.jpg',
            ],
            [
                'image'=>'img/07/07.jpg',
            ],
            [
                'image'=>'img/07/08.jpg',
            ],
            [
                'image'=>'img/07/09.jpg',
            ],
            [
                'image'=>'img/07/10.jpg',
            ],
            [
                'image'=>'img/07/11.jpg',
            ],
            [
                'image'=>'img/07/12.jpg',
            ],
        ]);

        Tour::where('id',8)->first()->image_tour()->createMany([
            [
                'image'=>'img/08/01.jpg',
            ],
            [
                'image'=>'img/08/02.jpg',
            ],
            [
                'image'=>'img/08/03.jpg',
            ],
            [
                'image'=>'img/08/04.jpg',
            ],
            [
                'image'=>'img/08/05.jpg',
            ],
            [
                'image'=>'img/08/06.jpg',
            ],
            [
                'image'=>'img/08/07.jpg',
            ],
            [
                'image'=>'img/08/08.jpg',
            ],
            [
                'image'=>'img/08/09.jpg',
            ],
            [
                'image'=>'img/08/10.jpg',
            ],
            [
                'image'=>'img/08/11.jpg',
            ],
            [
                'image'=>'img/08/12.jpg',
            ],
        ]);

        Tour::where('id',9)->first()->image_tour()->createMany([
            [
                'image'=>'img/09/01.jpg',
            ],
            [
                'image'=>'img/09/02.jpg',
            ],
            [
                'image'=>'img/09/03.jpg',
            ],
            [
                'image'=>'img/09/04.jpg',
            ],
            [
                'image'=>'img/09/05.jpg',
            ],
            [
                'image'=>'img/09/06.jpg',
            ],
            [
                'image'=>'img/09/07.jpg',
            ],
            [
                'image'=>'img/09/08.jpg',
            ],
            [
                'image'=>'img/09/09.jpg',
            ],
            [
                'image'=>'img/09/10.jpg',
            ],
            [
                'image'=>'img/09/11.jpg',
            ],
            [
                'image'=>'img/09/12.jpg',
            ],
        ]);
    }
}
